### PR TITLE
Add zip file with patch and instructions for 14870, FDS conversion patch for Welcome to New Clu Clu Land

### PR DESCRIPTION
**Pull request by chadfraser**
This adds the patch that converts Clu Clu Land (USA) (GameCube Edition).nes to an NES equivalent of the FDS Welcome to New Clu Clu Land, along with the readme.txt file

Readme includes reference to the original author and source of the patch file

### CODE REVIEW

**Comment by televandalist** [comment]
That game ID in the zip name is `14780`, but it should be `14870`. 

I used the patch on my copy of `Clu Clu Land (USA) (GameCube Edition).nes` and this was the result:
RALibretro_41I7mO6ldT

It still loaded the entry for the game, so the RA Hash matched. 

The ROM info in the readme does not match the dump [No Intro's database](https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=2647) so the problem is probably somewhere in there...

**Comment by chadfraser** [comment]
Ah, thanks for the catch on the game ID, I'll fix that right away

Regarding the ROM Info in the file, are you patching it with a ROM that matches the info in the file? The one on No Intro's database linked there is for "Clu Clu Land (World) (GameCube Edition).nes" -- note that it's "(World) (GameCube Edition)", not "(USA) (GameCube Edition)" which the patch requires.

I'm not seeing the (USA) (Gamecube Edition) on No Intro's database there, but it's listed as a No Intro source on the regular Clu Clu Land's set's list of linked files, so I assumed that was accurate

**Comment by televandalist** [comment]
Looks like you were going by the hash info in the forum, which isn't current + seems to be incorrect anyway. However, I did get your patch working with `Clu Clu Land (J-AC).nes`, which is a GoodTools base. 

I redid the patch and made one to work with `Clu Clu Land (World).nes`, `Clu Clu Land (World) (Virtual Console).nes`, and `Clu Clu Land (World) (GameCube Edition).nes`. - Here's the link: https://github.com/RetroAchievements/RAPatches/raw/main/NES/FDSConversion/14870-NewCluCluLand-FDSConversion.zip

I'll close this PR once you confirm they work for you + link to the set.

**Comment by chadfraser** [comment]
Thanks for the help on these!

Confirmed that those work with the set - they seem to all produce an output file with the same hash as the previous patched output, `0C4F98ACE862FEB863717EC925DBC6D7`, so they're all already linked to the set. Unsure if that suggests I did something incorrect in testing, or if that's to be expected from the fixes you've made.

**Pull request closed without merging**
