### PR TITLE
Adding Money Glitch Fix for Tokyo Xtreme Racer 3

### PR DESCRIPTION
**Pull request by Kinglink**
Created this fix, already linked the new hash. 

Fixes a bug in the game which made the game unable to be completed by making two characters have abnormal large requirements (yen to Dollar conversion reduced CP by a factor of 100, but didn't change this requirement). 

20 years later, it's time to fix it.

### CODE REVIEW

**Comment by Blazekickn** [comment]
Why not divide everything by 100 instead of only those 2 fights? that way it matches the japanese version and the game isn't easier than originally intended.

**Comment by Kinglink** [comment]
These are the only two requirements that check the Credit value (CP in game)  

The value of everything has been divided by 100 in localization but the glitch is the developers didn't modify these two requirements.

**Comment by Blazekickn** [comment]
Oh, so its not that they put the value over the money cap or whatever like i heard, its that it requires specific values that aren't possible to have because everything has 00 slapped on the end?

**Comment by Kinglink** [comment]
I think you understand, but yeah, essentially what I think happens is localization went through and divided the starting credits, by 100 (4 mill to 40k) they divided the money earned in the game by 100,  They divided the max money cap by 100 (it's now 100 million - 1 so 99,999,999) but didn't update the requirements which now would be unreachable.  

Thinking about it, I suppose it makes sense if they never tested the full localization or had anyone do a full run through because everything they'd be able to find early on in the game was caught, both of these racers are relatively late game.

**Pull request merged**
